function mustBeSingleString(value)
    assert((ischar(value) && length(value) == numel(value)) ||...
        isstring(value) && isscalar(value),...
        'Must be scalar string or character vector.');
end